# Generated by Django 2.0.4 on 2018-04-26 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Number_Player', models.IntegerField()),
                ('DmName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('Campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='DmTools.Campaigns')),
            ],
        ),
    ]
