# Generated by Django 2.0.4 on 2018-04-28 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('Name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('Number_Player', models.IntegerField(null=True)),
                ('DmName', models.CharField(max_length=150)),
                ('Password', models.CharField(default='password', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campaign', models.CharField(max_length=500)),
                ('DM', models.CharField(max_length=150)),
                ('User', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('Campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DmTools.Campaigns')),
            ],
        ),
    ]
