# Generated by Django 2.0.4 on 2018-04-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DmTools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='Character',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
