# Generated by Django 2.0.4 on 2018-04-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DmTools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigns',
            name='id',
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='Name',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
