# Generated by Django 2.0.4 on 2018-04-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DmTools', '0002_players_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='Acrobatics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='Alignment',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='characters',
            name='AnimalHandling',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='Arcana',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='ArcaneRecovery',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AddField(
            model_name='characters',
            name='ArmorClass',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='Athletics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='Background',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='characters',
            name='Bonds',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AddField(
            model_name='characters',
            name='Cantrips',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='characters',
            name='Charisma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='ClassLevel',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='characters',
            name='Constituion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='Darkvision',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='characters',
            name='Deception',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='Dexterity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='Equipment',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AddField(
            model_name='characters',
            name='ExpierincePoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='FeyAncestry',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AddField(
            model_name='characters',
            name='Flaws',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AddField(
            model_name='characters',
            name='History',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='HitPointMaximum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='Ideals',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AddField(
            model_name='characters',
            name='Inititative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='Insight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='Intelligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='Intimidation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='Investigation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='Languages',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='characters',
            name='Medicine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='Nature',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='PassiveWisdom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='Perception',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='Performance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='PersonalityTraits',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='characters',
            name='Persuasion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='PreparedSpells',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AddField(
            model_name='characters',
            name='ProficencyBonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='Proficiencies',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='characters',
            name='Race',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='characters',
            name='Religion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='ShelterOfTheFaithful',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AddField(
            model_name='characters',
            name='SleightOfHand',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='Speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='SpellSlots',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AddField(
            model_name='characters',
            name='Spellbook',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='characters',
            name='SpellcastingAbility',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='characters',
            name='Stealth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='Strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='Survival',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characters',
            name='Trance',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AddField(
            model_name='characters',
            name='Wisdom',
            field=models.IntegerField(default=0),
        ),
    ]
