# Generated by Django 2.0.4 on 2018-04-26 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DmTools', '0002_auto_20180426_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='Campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DmTools.Campaigns'),
        ),
    ]
