# Generated by Django 2.0.4 on 2018-04-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DmTools', '0003_auto_20180426_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='Number_Player',
            field=models.IntegerField(null=True),
        ),
    ]
