# Generated by Django 2.0.4 on 2018-04-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DmTools', '0004_auto_20180426_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campaign', models.CharField(max_length=500)),
                ('DM', models.CharField(max_length=150)),
                ('User', models.CharField(max_length=150)),
            ],
        ),
    ]
