# Generated by Django 2.0.4 on 2018-04-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DmTools', '0005_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='Password',
            field=models.CharField(default='password', max_length=50),
        ),
    ]
